# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 329c0b52ed3c037d719e5732a6c652b050e53568652ff4e06910f7d62cca0e16040e8dfb39d0b2c1d5f55107b64bcaa765bfbecda58d4f22535031f2cee76626

test:
  secret_key_base: f8a4d2f7e1070f318bf0957072014a3df24375f5d287610a6131da0af27937bfec49dd0905014d94a055543901c4bd78d29645c410d2b27ccc342383de4459ec

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
